name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: |
        pip install --upgrade pip
        make install
	    jupytext --to notebook notebooks/*.py
        rm notebooks/*.py
    - run: |
        git add .
        git config --global user.email "none"
        git config --global user.name "github-actions-bot"
        git commit -m "build notebooks"
        git push -f origin HEAD:gh-pages