name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: [3.7]
          tensorflow: ["~=2.6.0"]
    name: Python-${{ matrix.python-version }} tensorflow${{ matrix.tensorflow }}
    env:
      VERSION_TF: ${{ matrix.tensorflow }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        make install
    - name: Run tests
      run: make test

  docs:
    needs: check-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: [3.7]
          tensorflow: ["~=2.6.0"]
    name: Python-${{ matrix.python-version }} tensorflow${{ matrix.tensorflow }}
    env:
      VERSION_TF: ${{ matrix.tensorflow }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        make install
    - name: build documentation
      run: |
        make docs
        TMP_DIR=$(mktemp -d -p $(pwd))
        mv docs/_build/html/* $TMP_DIR
        rm -rf docs
        mv $TMP_DIR docs
        touch docs/.nojekyll
    - name: push documentation
      run: |
        git add .
        git config --global user.email "none"
        git config --global user.name "github-actions-bot"
        git commit -m "build documentation"
        git push -f origin HEAD:gh-pages
